channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - bioconda::advntr==1.2.0 # use 1.2.0 instead of 1.5.0 b/c conda complains about tensorflow-estimator when trying to install 1.5.0
