name: Docker

on:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        envname: [haptools, trtools]
        include:
          -
            name: github
            registry: ghcr.io
            username_secret: ${{ github.actor }}
            password_secret: ${{ github.token }}
          -
            name: google
            registry: gcr.io
            username_secret: GCR_USERNAME
            password_secret: GCR_JSON_KEY

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ matrix.registry }}
          username_secret: ${{ secrets[matrix.username_secret] }}
          password_secret: ${{ secrets[matrix.password_secret] }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.registry }}/${{ env.IMAGE_NAME }}-${{ matrix.envname }}

      - name: prune
        run: docker system prune -af

      - name: Build and push Docker image
        id: builder
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ (hashFiles(format('{0}/Dockerfile', matrix.envname )) != '')  && format('{0}/Dockerfile', matrix.envname) || 'Dockerfile' }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            "envname=${{ matrix.envname }}"
